

export const BlogData= [

    {
        id: 1,
        title: `Flags 'a Flying - and We Keep on Buying`,
        title2: '',
        date: `March 31st, 2023`,
        img_1_url: 'https://drive.google.com/uc?export=view&id=1RzWZax_MPf3Oqzuxz54nzQ_eZ3t952e7',
        img_2_url: '',
        img_3_url: '',
        img_4_url: '',
        img_5_url: '',
        img_6_url: '',
        img_7_url: '',
        img_8_url: '',
        img_9_url: '',
        img_10_url: '',
        img_1_captions: 'We COULD complain about the weather slowing down our traffic a bit this week, but we had plenty to do getting ready for YOU... and we REALLY appreciate your appreciation!',
        img_2_captions: 'Also just in - an AMAZING selection of Dahlias and Peonies, including ITOH!',
        img_3_captions: `And the convenient 4 lb packages of our fertilizers, plus an iron supplement:`,
        img_4_captions: `Our final gardening seminar is coming up on April 1. Learn all about BEES, extremely informative presentation even if you don't want to be a "keeper".`,
        img_5_captions: ``,
        img_6_captions: ``,
        img_7_captions: ``,
        img_8_captions: ``,
        img_9_captions: ``,
        img_10_captions: ``,
        link: '',
        link2: '',
        icon: '',
        icon2: ``,
        icon3: ``,
        intro: 'Multiple delivers of veggies and color this week and our staff continues to do an amazing job getting it on display. Be sure you visit our home page and check out the new slide show. Even better, take a personal tour! For example, we have an amazing selection of berries, potatoes, garlic, onions & more!',
        body_1:'  PLUS Russian pomegranate, globe willows, weeping willows, sycamores, and more trees and shrubs. YOU ASKED and WE FOUND THEM! BIG NEWS in the water conservation department! We have negotiated an incredible deal on a truckload of rain barrels, expected to arrive Friday. We are dropping our regular price from $149.99 to $129.99 and having a truckload sale at $100!! If you are an Albuquerque Water Authority customer, these also qualify for a $25 REBATE!',
        body_2: '',
        body_3: '',
        body_4: '',
        conclusion: `Thanks for being part of our family, and we look forward to seeing you soon.
        Richard, Jennifer, and Your Gardening Angels`,
        span_green: '',
        span_yellow: '',
        span_brown: ''
    },
    {
        id: 2,
        title: `Come fly with us...`,
        title2: '',
        date: `April 6th, 2023`,
        body_img_1: 'https://drive.google.com/uc?export=view&id=1jRKwSEJqO1wyX-jIvY11my2vqmaUFLRA',
        body_img_2: '',
        body_img_3: 'https://drive.google.com/uc?export=view&id=1s0NAi_GC4mpseNXhBXq7OXBBVt6jtMS-',
        body_img_4: '',
        img_1_url: 'https://drive.google.com/uc?export=view&id=10VbS4TwSJ5wwnss4duIhdjX2hZbYCmmu',
        img_2_url: 'https://drive.google.com/uc?export=view&id=1SXaZZ6az09tlJmZrTJfzs3uAbGRcJWmM',
        img_3_url: 'https://drive.google.com/uc?export=view&id=1Tibo5o6eYSi700NaMGYSXAzlefD8jjQ9',
        img_4_url: 'https://drive.google.com/uc?export=view&id=1jRKwSEJqO1wyX-jIvY11my2vqmaUFLRA',
        img_5_url: 'https://drive.google.com/uc?export=view&id=1zi-OU-mFZsUIi0pnDmbLXv9Ipnedr8jq',
        img_6_url: 'https://drive.google.com/uc?export=view&id=1SxFPygg4vJK1Ho4rSNfP2PCw5x6Mz96K',
        img_7_url: '',
        img_8_url: '',
        img_9_url: '',
        img_10_url: 'https://drive.google.com/uc?export=view&id=1qunr0U8nllBJfMYkaYWeN5Ci2S3k1yjQ',
        img_1_captions: 'We decided to do some product testing yesterday... in 35 mph winds. The kite passed... dare we say it... with flying colors, but the trellised golden euonymus shrubs needed some assistance.',
        img_2_captions: '',
        img_3_captions: ``,
        img_4_captions: ``,
        img_5_captions: ``,
        img_6_captions: ``,
        img_7_captions: ``,
        img_8_captions: ``,
        img_9_captions: ``,
        img_10_captions: ``,
        link: 'Kites AND Euanomys are on sale this week. Visit our SPECIALS page to see what else.',
        link2: '',
        icon: '',
        icon2: ``,
        icon3: ``,
        intro: 'There was an accidental duplication on our order of oodles this week, so we actually got oodles AND oodles of the most glorious color and the most luscious fresh green we have ever seen, and with more truckloads already on the way, we had to do some rack stacking. Help us make some room, will ya?',
        body_1:'If you want to try a new variety of tomatoes or peppers or make sure you get your FAVORITE, you will likely not find a better selection anywhere the entire season. Your Gardening Angels will give you the Secret Sauce for taking care of these plants early in the season and making sure they thrive, and also explain which herbs and veggies can be planted immediately with no concerns about frost.',
        body_2: 'Did you know we have a DELIVERY and PLANTING team? The Gardening Angels refer to them as the "ground crew" but they are experts in getting your trees and shrubs off to a great start. We have a fantastic selection, including wisteria, honeysuckle, flowering quince, evergreens, Indian Hawthorne shrubs and trees, and a forest of New Mexico grown PINIONS!!',
        body_3: 'Our final Gardening Seminar of the season is tomorrow, with beekeeper Justin Armstrong. Even if you never thought you would be keeping bees, Justin can show you how to keep bees without being a beekeeper. Keep that in mind and join us for this informative presentation. Or just say it 3 times fast.',
        body_4: '',
        conclusion: `Have a beeutiful day, and we'll see you again soon! -Richard, Jennifer, and Your Gardening Angels`,
        span_green: 'sahelllllo?',
        span_yellow: 'hello',
        span_brown: 'hello'
    },



   
    ]
    
