export const salesData= [
    {
        id: 1,
        name: 'Prickly Pear',
        img_url: `https://www.jerichonursery.com/wp-content/uploads/2023/04/PRICKLYPEAR.png`,
        description: 'Multiple different bloom colors --seetag',
        price: `$29.99`,
        discount: '',
        tagline: ``,
        start_date: '4/26/2023',
        expiration: '5/5/2023',
    },
    {
        id: 2,
        name: 'Helleores',
        img_url: `https://www.jerichonursery.com/wp-content/uploads/2023/04/HELLEBORE.jpg`,
        description: '(Lenten Rose)',
        price: '',
        discount: '20% off',
        tagline: ``,
        start_date: '4/26/2023',
        expiration: '5/5/2023',
    },
    {
        id: 3,
        name: 'Select Agave',
        img_url: `https://www.jerichonursery.com/wp-content/uploads/2023/04/agave.png`,
        description: 'see tag',
        price: '',
        discount: '20% off',
        tagline: ``,
        start_date: '4/26/2023',
        expiration: '5/5/2023',
    },
    {
        id: 4,
        name: `4 '' Tulips, Daffodils, Hyacinths, Grape Hyacinths, Dwarf Daffodils`,
        img_url: `https://www.jerichonursery.com/wp-content/uploads/2023/04/happy-bulbs.jpg`,
        description: 'regularly: $7.99',
        price: '',
        discount: 'now: $4 or 2 for $7 OR 7 for $20',
        tagline: ``,
        start_date: '4/26/2023',
        expiration: '5/5/2023',
    }]
    
